/**
 * Author:  Axel
 * Created: 6 déc. 2019
 */

CREATE TABLE TUTEUR
(
    mail VARCHAR(100) NOT NULL PRIMARY KEY,
    sexe VARCHAR(1),
    description VARCHAR(255) NOT NULL
);


CREATE TABLE NOTES
(
    id_notes INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    note INT NOT NULL,
    mail varchar(100) NOT NULL REFERENCES TUTEUR(MAIL)
);


CREATE TABLE INTERETS
(
    id_interets INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    Categorie VARCHAR(100) NOT NULL,
    mail VARCHAR(100) NOT NULL REFERENCES TUTEUR(MAIL)
);